"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { useStore, SavedReport } from "../../store/useStore";
import { useLanguage } from "../../context/LanguageContext";
import { Header } from "../../components/Header";
import { BottomNav } from "../../components/BottomNav";
import { motion, AnimatePresence } from "framer-motion";
import { PieChart, Pie, Cell, ResponsiveContainer, Legend, Tooltip } from "recharts";
import { 
  FileText, Calendar, Sparkles, X, ChevronRight, 
  TrendingUp, AlertCircle, Share2, Award, Briefcase, Receipt
} from "lucide-react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { RiyalSymbol } from "../../components/RiyalSymbol";

export default function ReportsPage() {
  const router = useRouter();
  const { t, language, isRtl } = useLanguage();
  const { user, savedReports, fetchSavedReports, loading } = useStore();

  const [selectedReport, setSelectedReport] = useState<SavedReport | null>(null);
  const [mounted, setMounted] = useState(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const handleSharePDF = async () => {
    if (!selectedReport) return;
    try {
      const chartEl = document.getElementById("chart-container-history");
      let chartImgData = "";
      if (chartEl) {
        const chartCanvas = await html2canvas(chartEl, {
          scale: 2,
          useCORS: true
        });
        chartImgData = chartCanvas.toDataURL("image/png");
      }

      const tempDiv = document.createElement("div");
      tempDiv.style.position = "absolute";
      tempDiv.style.left = "-9999px";
      tempDiv.style.top = "-9999px";
      tempDiv.style.width = "595px";
      tempDiv.style.backgroundColor = "#FFFFFF";
      tempDiv.style.color = "#1B2A4A";
      tempDiv.style.fontFamily = "sans-serif";
      tempDiv.style.padding = "40px";
      tempDiv.style.boxSizing = "border-box";
      
      tempDiv.style.direction = isRtl ? "rtl" : "ltr";

      const headerTitle = isRtl ? "معك | مصرف الإنماء" : "Ma3ak | Alinma Bank";
      const reportTitle = isRtl ? "تقرير الأداء المالي" : "Financial Performance Report";
      const periodLabel = isRtl ? "الفترة" : "Period";
      const incomeLabel = isRtl ? "إجمالي الدخل" : "Total Income";
      const spentLabel = isRtl ? "إجمالي المصروفات" : "Total Expenses";
      const chartTitle = isRtl ? "توزيع المصروفات حسب الفئات" : "Expense Distribution by Category";
      const insightsTitleText = isRtl ? "التوصيات والتحليلات الذكية" : "Smart Recommendations & Insights";
      const footerText = isRtl ? "Generated by Ma3ak — مصرف الإنماء" : "Generated by Ma3ak — Alinma Bank";
      const sarText = isRtl ? `<svg viewBox="0 0 100 100" style="width: 1em; height: 1em; display: inline-block; vertical-align: -0.15em; fill: currentColor;"><path d="M 38 8 L 46 6.8 L 46 65 L 38 78 L 15 82 L 15 74 L 38 70 Z" /><path d="M 54 15 L 62 13.8 L 62 68 L 54 68 Z" /><path d="M 18 50 L 81 35 L 81 43 L 18 58 Z" /><path d="M 62 57 L 81 53 L 81 61 L 62 65 Z" /><path d="M 54 78 L 81 74 L 81 82 L 54 86 Z" /></svg>` : "SAR";

      const clientName = user?.full_name || (isRtl ? "أحمد العنزي" : "Ahmed Al-Enazi");

      tempDiv.innerHTML = `
        <div style="border: 2px solid #1B2A4A; padding: 30px; border-radius: 20px; background-color: #ffffff; box-shadow: 0 4px 20px rgba(0,0,0,0.05); font-family: 'Inter', 'Roboto', sans-serif;">
          <!-- Header -->
          <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #7C6FD4; padding-bottom: 15px; margin-bottom: 20px;">
            <span style="font-size: 22px; font-weight: 900; color: #1B2A4A;">${headerTitle}</span>
            <span style="font-size: 14px; font-weight: bold; color: #7C6FD4;">${reportTitle}</span>
          </div>

          <!-- Client Name & Period -->
          <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; background-color: #FDF9F3; padding: 10px 15px; border-radius: 10px; border: 1px solid rgba(212,117,75,0.2); font-size: 12px; font-weight: bold;">
            <span style="color: #1B2A4A;">
              ${isRtl ? "العميل" : "Client"}: <span style="color: #7C6FD4;">${clientName}</span>
            </span>
            <span style="color: #D4754B;">
              ${periodLabel}: ${selectedReport.title.split(" - ")[1] || ""}
            </span>
          </div>

          <!-- Income & Expense Grid -->
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 25px;">
            <div style="background-color: #EBF7EE; border: 1px solid #D1F0D9; padding: 15px; border-radius: 15px; text-align: center;">
              <span style="font-size: 11px; font-weight: bold; color: #2E7D4F; display: block; margin-bottom: 5px;">${incomeLabel}</span>
              <span style="font-size: 16px; font-weight: 900; color: #2E7D4F;">+${selectedReport.total_income.toLocaleString()} ${sarText}</span>
            </div>
            <div style="background-color: #FCECEB; border: 1px solid #F9D6D4; padding: 15px; border-radius: 15px; text-align: center;">
              <span style="font-size: 11px; font-weight: bold; color: #C0392B; display: block; margin-bottom: 5px;">${spentLabel}</span>
              <span style="font-size: 16px; font-weight: 900; color: #C0392B;">-${selectedReport.total_spent.toLocaleString()} ${sarText}</span>
            </div>
          </div>

          <!-- Chart -->
          ${chartImgData ? `
          <div style="text-align: center; margin-bottom: 25px;">
            <span style="font-size: 12px; font-weight: bold; color: #1B2A4A; display: block; text-align: ${isRtl ? "right" : "left"}; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 5px;">${chartTitle}</span>
            <img src="${chartImgData}" style="width: 100%; max-width: 350px; height: auto; margin: 0 auto; display: block;" />
          </div>
          ` : ""}

          <!-- Insights -->
          <div style="background-color: #FDF7F5; border: 1px solid #FADED3; padding: 20px; border-radius: 15px; margin-bottom: 25px;">
            <div style="font-size: 13px; font-weight: 900; color: #D4754B; margin-bottom: 10px; display: flex; align-items: center; gap: 5px;">
              <span>✨ ${insightsTitleText}</span>
            </div>
            <ul style="margin: 0; padding-${isRtl ? "right" : "left"}: 20px; font-size: 11px; font-weight: bold; color: #1B2A4A; line-height: 1.8;">
              ${selectedReport.insights.filter((ins: string) => !ins.includes("قرار تمويلي رسمي") && !ins.includes("financing decision")).map((insight: string) => `<li style="margin-bottom: 8px;">${insight}</li>`).join("")}
            </ul>
          </div>

          <!-- Footer -->
          <div style="border-top: 1px solid #eee; padding-top: 15px; text-align: center; font-size: 10px; font-weight: bold; color: #999;">
            ${footerText}
          </div>
        </div>
      `;
      document.body.appendChild(tempDiv);

      const pdfCanvas = await html2canvas(tempDiv, {
        scale: 2,
        useCORS: true
      });
      document.body.removeChild(tempDiv);

      const imgData = pdfCanvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const imgWidth = 210;
      const imgHeight = (pdfCanvas.height * imgWidth) / pdfCanvas.width;
      
      pdf.addImage(imgData, "PNG", 0, 0, imgWidth, imgHeight);
      pdf.save(`Ma3ak_Report_${selectedReport.title.replace(/\s+/g, "_")}.pdf`);
      
      setToastMessage(isRtl ? "تم تحميل التقرير كـ PDF ✓" : "PDF downloaded successfully ✓");
      setTimeout(() => {
        setToastMessage(null);
      }, 3000);
    } catch (err) {
      console.error("PDF generation error:", err);
      alert(isRtl ? "عذراً، فشل تصدير التقرير كـ PDF" : "Sorry, PDF export failed");
    }
  };

  useEffect(() => {
    setMounted(true);
    if (!user) {
      router.replace("/login");
    } else {
      fetchSavedReports();
    }
  }, [user, router, fetchSavedReports]);

  if (loading || !user) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-brand-cream text-brand-navy">
        <div className="w-8 h-8 border-4 border-brand-purple/20 border-t-brand-purple rounded-full animate-spin"></div>
      </div>
    );
  }

  const COLORS = ["#7C6FD4", "#D4754B", "#1B2A4A", "#2E7D4F", "#C0392B", "#9B59B6", "#1ABC9C", "#95A5A6"];

  return (
    <div className="min-h-screen md:min-h-0 bg-brand-cream md:bg-transparent pb-24 md:pb-0 max-w-md md:max-w-none mx-auto md:mx-0 relative shadow-2xl md:shadow-none flex flex-col">
      
      {/* TOAST NOTIFICATION */}
      <AnimatePresence>
        {toastMessage && (
          <motion.div
            initial={{ opacity: 0, y: -50, x: "-50%" }}
            animate={{ opacity: 1, y: 20, x: "-50%" }}
            exit={{ opacity: 0, y: -50, x: "-50%" }}
            className="fixed top-0 left-1/2 transform -translate-x-1/2 z-50 bg-[#2E7D4F] text-white px-6 py-3 rounded-full text-xs font-black shadow-lg flex items-center gap-2"
          >
            <span>{toastMessage}</span>
          </motion.div>
        )}
      </AnimatePresence>

      <Header title={t("reportsHistoryTitle")} />

      <main className="px-5 pt-4 md:px-0 md:pt-0 space-y-4 flex-grow animate-slide-up">
        
        <p className="text-[10px] font-bold text-brand-navy/50 px-1 uppercase tracking-wider">
          {isRtl ? "سجلات التحليل المالي المحفوظة" : "Archived AI Financial Audits"}
        </p>

        {savedReports.length === 0 ? (
          <div className="bg-white rounded-3xl p-8 border border-brand-navy/5 shadow-sm text-center space-y-4">
            <div className="w-14 h-14 bg-brand-purple/10 flex items-center justify-center rounded-2xl text-brand-purple mx-auto">
              <FileText className="w-6 h-6 animate-pulse" />
            </div>
            <p className="text-xs font-bold text-brand-navy/60 leading-relaxed max-w-xs mx-auto">
              {t("noReportsYet")}
            </p>
            <motion.button
              whileTap={{ scale: 0.95 }}
              onClick={() => router.push("/chat")}
              aria-label={isRtl ? "اطلب تقريراً الآن" : "Generate One Now"}
              className="px-6 py-2.5 bg-brand-navy text-white rounded-xl text-[10px] font-black shadow-md hover:bg-brand-navy/95 transition-all duration-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-navy focus-visible:ring-offset-2"
            >
              {isRtl ? "اطلب تقريراً الآن" : "Generate One Now"}
            </motion.button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {savedReports.map((report) => (
              <motion.div
                key={report.id}
                whileHover={{ scale: 1.01, y: -1 }}
                whileTap={{ scale: 0.99 }}
                onClick={() => setSelectedReport(report)}
                className="bg-white rounded-2xl p-4 shadow-sm border border-brand-navy/5 flex items-center justify-between cursor-pointer transition-all duration-200 hover:border-brand-purple/20 hover:shadow-md"
              >
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-brand-purple/10 flex items-center justify-center rounded-xl text-brand-purple">
                    <FileText className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="text-xs font-black text-brand-navy truncate max-w-[170px]">
                      {report.title}
                    </h4>
                    <span className="text-[9px] font-bold text-brand-navy/40 flex items-center gap-1 mt-0.5">
                      <Calendar className="w-3 h-3 text-brand-purple" />
                      {t("period")}: {report.title.split("-")[1] || t("appName")}
                    </span>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <div className="text-right">
                    <span className="text-[7px] font-bold text-brand-navy/40 uppercase block leading-none">
                      {t("totalSpent")}
                    </span>
                    <span className="text-[11px] font-black text-brand-danger">
                      -{report.total_spent.toLocaleString()} <RiyalSymbol size="1.05em" />
                    </span>
                  </div>
                  <ChevronRight className={`w-4 h-4 text-brand-navy/30 ${isRtl ? "rotate-180" : ""}`} />
                </div>
              </motion.div>
            ))}
          </div>
        )}

      </main>

      {/* DETAIL MODAL POPUP */}
      <AnimatePresence>
        {selectedReport && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-brand-navy/60 backdrop-blur-md flex items-end md:items-center justify-center p-0 md:p-4"
          >
            <motion.div
              initial={{ y: "100%" }}
              animate={{ y: 0 }}
              exit={{ y: "100%" }}
              transition={{ type: "spring", damping: 25, stiffness: 220 }}
              className="bg-white rounded-t-[32px] md:rounded-3xl w-full max-w-md max-h-[85vh] md:max-h-[90vh] overflow-y-auto p-6 relative border border-brand-navy/5 shadow-2xl space-y-5 text-right"
            >
              {/* Modal Header */}
              <div className="flex justify-between items-center pb-1 border-b border-brand-navy/5">
                <button
                  onClick={() => setSelectedReport(null)}
                  aria-label={isRtl ? "إغلاق" : "Close"}
                  className="p-2 rounded-full bg-brand-cream/50 text-brand-navy/60 hover:bg-brand-cream hover:text-brand-navy transition-all duration-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-purple flex items-center justify-center"
                >
                  <X className="w-5 h-5" />
                </button>
                <div className="flex items-center gap-2 text-brand-purple">
                  <Award className="w-5 h-5 text-brand-orange animate-bounce-slow" />
                  <h3 className="text-base font-black text-brand-navy">
                    {selectedReport.title}
                  </h3>
                </div>
              </div>

              {/* Saved Date */}
              <span className="text-[9px] font-bold text-brand-navy/40 block bg-brand-cream/15 px-3.5 py-2 rounded-xl border border-brand-navy/5">
                {t("savedOn")}: {new Date(selectedReport.saved_at).toLocaleString()}
              </span>

              {/* Total Grid */}
              <div className="grid grid-cols-2 gap-3.5">
                <div className="bg-gradient-to-br from-[#EBF7EE]/60 to-[#EBF7EE]/15 p-3.5 rounded-2xl border border-brand-success/15 shadow-[0_2px_8px_rgba(46,125,79,0.01)] text-right">
                  <span className="text-[8px] font-bold text-brand-navy/40 block uppercase tracking-wide">
                    {t("totalIncome")}
                  </span>
                  <span className="text-xs font-black text-brand-success block mt-0.5">
                    +{selectedReport.total_income.toLocaleString()} <RiyalSymbol size="1.05em" />
                  </span>
                </div>

                <div className="bg-gradient-to-br from-[#FCECEB]/60 to-[#FCECEB]/15 p-3.5 rounded-2xl border border-brand-danger/15 shadow-[0_2px_8px_rgba(192,57,43,0.01)] text-right">
                  <span className="text-[8px] font-bold text-brand-navy/40 block uppercase tracking-wide">
                    {t("totalSpent")}
                  </span>
                  <span className="text-xs font-black text-brand-danger block mt-0.5">
                    -{selectedReport.total_spent.toLocaleString()} <RiyalSymbol size="1.05em" />
                  </span>
                </div>
              </div>

              {/* Recharts PieChart Category Breakdown */}
              {mounted && selectedReport.top_categories.length > 0 && (
                <div id="chart-container-history" className="h-44 w-full bg-brand-cream/10 rounded-2xl border border-brand-navy/5 p-2 flex items-center justify-center">
                  <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                      <Pie
                        data={selectedReport.top_categories}
                        cx="50%"
                        cy="50%"
                        innerRadius={30}
                        outerRadius={50}
                        paddingAngle={3}
                        dataKey="amount"
                        nameKey="category"
                      >
                        {selectedReport.top_categories.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                        ))}
                      </Pie>
                      <Tooltip contentStyle={{ fontSize: "9px", borderRadius: "10px", padding: "5px" }} />
                      <Legend formatter={(value) => <span className="text-[11px] font-black text-brand-navy/80">{value}</span>} layout="vertical" align="right" verticalAlign="middle" iconSize={8} iconType="circle" />
                    </PieChart>
                  </ResponsiveContainer>
                </div>
              )}

              {/* Category Breakdown list with progress bars */}
              <div className="space-y-3 pt-1">
                <span className="text-[9px] font-black text-brand-navy/45 uppercase tracking-wider block">
                  {t("topCategories")}
                </span>
                {selectedReport.top_categories.map((cat, idx) => (
                  <div key={cat.category} className="space-y-1">
                    <div className="flex justify-between items-center text-[10px] font-bold text-brand-navy/80">
                      <span className="flex items-center gap-1.5">
                        <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: COLORS[idx % COLORS.length] }}></span>
                        {cat.category}
                      </span>
                      <span>
                        {cat.amount.toLocaleString()} <RiyalSymbol size="1.05em" /> ({cat.percentage}%)
                      </span>
                    </div>
                    <div className="w-full h-1.5 bg-brand-cream/40 rounded-full overflow-hidden border border-brand-navy/5 p-0.5">
                      <div 
                        className="h-full rounded-full transition-all duration-500 ease-out"
                        style={{ width: `${cat.percentage}%`, backgroundColor: COLORS[idx % COLORS.length] }}
                      ></div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Dynamic Saved Insights */}
              <div className="bg-gradient-to-br from-brand-orange/10 to-brand-orange/5 border border-brand-orange/20 rounded-2xl p-4.5 space-y-2.5 shadow-[0_2px_12px_rgba(212,117,75,0.02)]">
                <div className="flex items-center gap-1.5 text-brand-orange font-black text-[10px]">
                  <Sparkles className="w-4 h-4 animate-pulse" />
                  <span>{t("insightsTitle")}</span>
                </div>
                <ul className="list-inside text-[9.5px] font-bold text-brand-navy/70 space-y-1.5 leading-relaxed text-right">
                  {selectedReport.insights.map((insight, idx) => (
                    <li key={idx} className="relative pr-3">
                      <span className="absolute right-0 text-brand-orange">•</span>
                      {insight}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Actions */}
              <button 
                onClick={handleSharePDF}
                aria-label={isRtl ? "تصدير التقرير كـ PDF" : "Export Report as PDF"}
                className="w-full py-3.5 rounded-2xl bg-brand-navy text-white text-xs font-black shadow-md hover:bg-brand-navy/90 transition-all duration-200 flex items-center justify-center gap-1.5 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-navy focus-visible:ring-offset-2"
              >
                <Share2 className="w-4 h-4" />
                <span>{isRtl ? "تصدير التقرير كـ PDF" : "Export Report as PDF"}</span>
              </button>

            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <BottomNav activeTab="reports" />
    </div>
  );
}
